"""Evidence-Gated Memory — provenance-first memory for high-stakes AI agents."""

from evidence_gated_memory.core.memory import EvidenceGatedMemory
from evidence_gated_memory.core.entities import ExtractedEntity
from evidence_gated_memory.core.models import (
    CandidateAtom,
    CandidateGateResult,
    Claim,
    ConversationMessage,
    Evidence,
    Event,
    Fact,
    FactKind,
    Freshness,
    GateResult,
    MemoryAtom,
    MemoryCandidateDecision,
    MemoryCandidateStatus,
    MemoryAtomKind,
    MemoryPersona,
    MemoryScenario,
    OffloadRecord,
    SourceSpan,
    Task,
    TaskEdge,
    TaskEdgeKind,
    TaskNode,
    TaskNodeStatus,
    TaskState,
    TaskStatus,
    TransitionGateResult,
    TransitionResult,
)

__version__ = "0.4.0"

__all__ = [
    "EvidenceGatedMemory",
    "ExtractedEntity",
    "Event",
    "ConversationMessage",
    "CandidateAtom",
    "CandidateGateResult",
    "Evidence",
    "Claim",
    "Fact",
    "FactKind",
    "Freshness",
    "GateResult",
    "MemoryAtom",
    "MemoryCandidateDecision",
    "MemoryCandidateStatus",
    "MemoryAtomKind",
    "MemoryPersona",
    "MemoryScenario",
    "OffloadRecord",
    "SourceSpan",
    "Task",
    "TaskEdge",
    "TaskEdgeKind",
    "TaskNode",
    "TaskNodeStatus",
    "TaskState",
    "TaskStatus",
    "TransitionGateResult",
    "TransitionResult",
]
